name: Build jacoco-parser

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: jacoco-parser-${{ steps.get_version.outputs.version }}.zip
          path: build/distributions/jacoco-parser-${{ steps.get_version.outputs.version }}.zip
          if-no-files-found: error

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/distributions/jacoco-parser-${{ steps.get_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SHA
        id: shasum
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=sha::"$(shasum -a 256 build/distributions/jacoco-parser-${{ steps.get_version.outputs.version }}.zip | awk '{printf $1}')"

      - name: Bump Brew
        if: startsWith(github.ref, 'refs/tags/')
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          # Update to ensure we have the latest version which supports arbitrary default branches.
          brew update
          brew tap jdsingh/repo
          brew bump-formula-pr -f --no-browse --no-audit \
            --version=${{ steps.get_version.outputs.version }} \
            --sha256=${{ steps.shasum.outputs.sha }} \
            --url="https://github.com/jdsingh/jacoco-parser/releases/download/${{ steps.get_version.outputs.version }}/jacoco-parser-${{ steps.get_version.outputs.version }}.zip" \
            jdsingh/repo/jacoco-parser
